<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robotModel" nsURI="http://www.example.org/robotModel" nsPrefix="robotModel">
  <eClassifiers xsi:type="ecore:EClass" name="RML">
    <eOperations name="setup" eType="#//Void"/>
    <eOperations name="loop" eType="#//Void"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mouvement" upperBound="-1"
        eType="#//Mouvement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" eType="#//Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mouvement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LongitudinalMouvement" eSuperTypes="#//Mouvement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frontward" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LateralMouvement" eSuperTypes="#//Mouvement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RadialMouvement" eSuperTypes="#//Mouvement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clockwize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unit"/>
  <eClassifiers xsi:type="ecore:EClass" name="m" eSuperTypes="#//TranslationUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="deg" eSuperTypes="#//RotationUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="cm" eSuperTypes="#//TranslationUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="mm" eSuperTypes="#//TranslationUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="rad" eSuperTypes="#//RotationUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="TranslationUnit" eSuperTypes="#//Unit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="longitudinalmouvement"
        eType="#//LongitudinalMouvement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lateralmouvement" eType="#//LateralMouvement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RotationUnit" eSuperTypes="#//Unit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="radialmouvement" eType="#//RadialMouvement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clock" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Distance" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        upperBound="-1" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//Operator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interger" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArtimethicOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Plus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplication"/>
  <eClassifiers xsi:type="ecore:EClass" name="Division"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Remainder"/>
</ecore:EPackage>
